# Generated by Django 4.1.5 on 2023-03-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_address_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='cod',
        ),
    ]
